NetworkManager/NetworkManager-ci

- run/fedora-vagrant/nmtest
- run/fedora-vagrant/scripts/build.sh
- run/fedora-vagrant/scripts/runtest.sh
- run/fedora-vagrant/scripts/setup.sh
Add scripts for vagrant based execution on Fedora.
> fedora-vagrant: add nmtest vagrant utitili

- run/fedora-vagrant/nmtest
- run/fedora-vagrant/scripts/build.sh
* add static IP
* remove some virtualbox specific options
> vagrant: libvirt tune ups

- nmcli/features/environment.py
- testmapper.txt
testmapper: fix swapped ppp and pptp tests
env: fix process id print
> Misc fixes

- nmcli/features/ppp.feature
- testmapper.txt
https://bugzilla.redhat.com/show_bug.cgi?id=1478694
> ppp: add test for PPPoE over VLAN

- nmcli/features/environment.py
- nmcli/features/ipv6.feature
- nmcli/features/steps/steps.py
- testmapper.txt
https://bugzilla.redhat.com/show_bug.cgi?id=1470930
> IPv6: add test for preservation of cached routes

- nmcli/features/general.feature
- testmapper.txt
https://bugzilla.redhat.com/show_bug.cgi?id=1442361
> Add test @keep_external_device_enslaved_on_down

- nmcli/features/environment.py
- nmcli/features/wifi.feature
- nmcli/features/wifi_hwsim.feature
- prepare/hostapd_wired.sh
- prepare/hostapd_wireless.sh
- str_setup_definition.ini
- testmapper.txt
* mac80211_hwsim based wireless tests
* wpa2-psk and 802.1x (tls/ttls/peap) based tests included only
* add headers for better logging
> marge simwifi tests to master 

- nmcli/features/gsm.feature
> gsm: connectivity check may jump from none to full (no limited)

- nmcli/features/environment.py
> simwifi: limit execution to x86_64 only

- str_setup_definition.ini
install kernel and reboot if on x86_64 or exit 0 just before NM compilation
> sth: use patched rhel7 kernel with mac802_simhw module

- nmcli/features/bond.feature
it looks 10000 is too large and 1000 works always
> bond: decrease bond arp interval

- nmcli/features/environment.py
- nmcli/features/pptp.feature
not sure what exactly was wrong but this seems to work again
> pptp: fixes for pptp password

- nmcli/features/dcb.feature
- nmcli/features/environment.py
- nmcli/features/ethernet.feature
- nmcli/features/sriov.feature
- nmcli/features/steps/steps.py
- prepare/devsetup.sh
Tests need to use new devices and drivers.
> wol/dcb/sriov: move to new machine

- nmcli/features/general.feature
check for (119|118|117) seconds as a real lifetime refresh
> general: runonce check for more seconds

- nmcli/features/steps/steps.py
stop NM, delete devices and then start it again
> steps: rewrite reboot

- nmcli/features/environment.py
- nmcli/features/vpn.feature
- testmapper.txt
fix pptp tests to work together with other vpn tests
> vpn keep username from data deduplication and fix

- str_setup_definition.ini
fix for https://bugzilla.redhat.com/show_bug.cgi?id=1494065 as discussed here:
https://bugzilla.gnome.org/show_bug.cgi?id=788368
> sth: add new patched glib2 version to prevent crashes

- nmcli/features/ipv4.feature
Test need to be executed on eth0 so it's able to ping outer world
> reload_dns need to be executed on eth0

- nmcli/features/environment.py
> env: change openvpn clean to run before libreswan

- str_setup_definition.ini
> hwsim: add new kernel for hwsim wifi testing

- nmcli/features/ipv6.feature
>  ipv6: add ipv4 may fail no if waiting for ipv4 info too #54

- nmcli/features/ethernet.feature
- prepare/hostapd_wired.sh
verification for https://bugzilla.redhat.com/show_bug.cgi?id=1438476
> 8021x: 1.10+ auto connected profile w/o password test

- nmcli/features/general.feature
- testmapper.txt
move test in testmapper 
add sleep 3 between NM and network services restart
> move run_once_helper_for_localhost_localdomain to ipv4 section

- nmcli/features/infiniband.feature
fixed 1.10 version as MTU/MAC/Parent interface/P_KEY order was changed.
> inf: novice mode for port was changed

- nmcli/features/connection.feature
> either [0] or [none] check in connection_user_settings_data

- nmcli/features/bridge.feature
- nmtui/features/bridge.feature
- testmapper.txt
* add addition to gfm 8
* modify it to 0 (aka remove it)
* add it via nmtui
https://bugzilla.redhat.com/show_bug.cgi?id=1358615
> bridge: add tests for group-forward-mask

- nmcli/features/environment.py
- nmcli/features/ipv4.feature
- testmapper.txt
* add inifnity alias test
* add configuration file only test
https://bugzilla.redhat.com/show_bug.cgi?id=1350830
> ipvr: add a bunch of dhcp-timout tests

- nmcli/features/connection.feature
- nmcli/features/general.feature
- nmcli/features/ipv4.feature
- nmcli/features/ipv6.feature
- nmtui/features/ipv4.feature
- nmtui/features/ipv6.feature
route metric: adding route was slightly reworked
> route metric: adding route was slightly reworked

- nmcli/features/environment.py
- nmcli/features/general.feature
- run/centos-ci/scripts/prepare_box.sh
- testmapper.txt
Modify a connection that has a rule- file.
https://bugzilla.redhat.com/show_bug.cgi?id=1384799
@Build:nm-1-10
> general: add 'modify_policy_based_routing_connection'

- nmcli/features/general.feature
> general: remove surplus allow_wired_connections tag

- nmcli/features/ipv4.feature
- testmapper.txt
Check that NM can add mupltiple ip addresses via ip4 option.
https://bugzilla.redhat.com/show_bug.cgi?id=1482772
@Build:nm-1-10
> ipv4: add 'ipv4_multiple_ip4' test

- nmcli/features/environment.py
- nmcli/features/ipv4.feature
- testmapper.txt
Reverts NetworkManager/NetworkManager-ci#118
> Revert "ipv4: add 'ipv4_set_very_long_dhcp_client_id' test"

- nmcli/features/ipv4.feature
- testmapper.txt
Reverts NetworkManager/NetworkManager-ci#119
> Revert "ipv4: add 'ipv4_restore_default_route_externally' test"

- nmcli/features/ipv4.feature
- testmapper.txt
* ipv4_set_very_long_dhcp_client_id
https://bugzilla.redhat.com/show_bug.cgi?id=1531173
* ipv4_restore_default_route_externally
https://bugzilla.redhat.com/show_bug.cgi?id=1503769
@Build:nm-1-10
> ipv4: add two tests

- nmcli/features/environment.py
- nmcli/features/general.feature
- testmapper.txt
Exercise connectivity checker via dbus a bit.
https://bugzilla.redhat.com/show_bug.cgi?id=1534477
@Build:nm-1-10
> general: add 'manipulate_connectivity_check_via_dbus' test

- run/utils/j-dump/README.txt
- run/utils/j-dump/j-dump.py
- run/utils/j-dump/jdcron.sh
Script to collect and summarize results from NetworkManager jenkins jobs.
It is a bit rough and would need some improvement... but could be already useful.
> j-dump: add script to collect and summarize job results from jenkins

- nmcli/features/team.feature
https://bugzilla.redhat.com/show_bug.cgi?id=1538699
@Build:nm-1-10
> team: bring back random team runner support

- nmcli/features/environment.py
- nmcli/features/ovs.feature
- testmapper.txt
https://bugzilla.redhat.com/show_bug.cgi?id=1540063
@Build:nm-1-10
> ovs: add reconnect/reboot tests

- nmcli/features/ovs.feature
> ovs: add 'NM_reboot_openvswitch_vlan_configuration' test

- nmcli/features/gsm.feature
* https://bugzilla.redhat.com/show_bug.cgi?id=1460217
@Build:nm-1-10
> gsm: add nmcli mtu check

- nmcli/features/general.feature
Note: the test is still broken on master.
> general: device_reapply_routes: fix regexp

- nmcli/features/general.feature
* delay enabling of firewall when connectivity check is disabled
* delay device down when upping it for delayed up
@Build:nm-1-10
> general: few stability fixes

- nmcli/features/tc.feature
- run/centos-ci/build_python_script.py
- testmapper.txt
* set_fq_codel_queue
* set_pfifo_fast_queue
not sure if anything else works now
https://bugzilla.redhat.com/show_bug.cgi?id=909236
@Build:nm-1-10
> tc: add qdiscs tests

- nmcli/runtest.sh
- nmtui/runtest.sh
> runtest.sh: use full paths instead of relative ones (need for STR)

- mapper.yaml
No effects to production, current ci code will ignore the file until
switched.
> Add mapper draft.

- nmcli/features/alias.feature
- nmcli/features/bond.feature
- nmcli/features/bridge.feature
- nmcli/features/connection.feature
- nmcli/features/environment.py
- nmcli/features/ethernet.feature
- nmcli/features/general.feature
- nmcli/features/ipv4.feature
- nmcli/features/ipv6.feature
- nmcli/features/steps/steps.py
- nmcli/features/team.feature
- nmcli/features/vlan.feature
- nmcli/features/wifi_hwsim.feature
- prepare/devsetup.sh
- prepare/hostapd_wired.sh
- prepare/hostapd_wireless.sh
- prepare/vethsetup.sh
- tmp/dbus-set-gw.py
- tmp/radvd.conf
- tmp/repro_1401515.py
> migrate features to different devices for parallelization

- mapper.yaml
- nmcli/features/vlan.feature
Test new code with the github trigger
> Test new code with the github trigger

- nmcli/features/environment.py
- nmcli/features/general.feature
- nmcli/features/ipv4.feature
- nmcli/features/ipv6.feature
- nmcli/features/steps/steps.py
- prepare/hostapd_wireless.sh
few minor fixed
@Build:nm-1-10
> ipv4/6: reload used via dbus rather than systemctl

- nmtui/features/ipv4.feature
- nmtui/features/ipv6.feature
Eth0's routes were moved to 99 so we need to reflect that.
> nmtui: set routes check a bit better

- nmcli/features/environment.py
- nmcli/features/steps/steps.py
- run/centos-ci/build_python_script.py
do service restart instead reload in centos and NM 1.10-
@Build:nm-1-10
> centos tweaks

- nmcli/features/connection.feature
- nmcli/features/environment.py
- nmcli/features/general.feature
- nmcli/features/team.feature
- nmcli/features/tuntap.feature
- tmp/repro_1433303.sh
> all: bond/team/bridge device name separation

- nmcli/features/alias.feature
- nmcli/features/bond.feature
- nmcli/features/bridge.feature
- nmcli/features/connection.feature
- nmcli/features/ethernet.feature
- nmcli/features/general.feature
- nmcli/features/gsm.feature
- nmcli/features/ipv4.feature
- nmcli/features/steps/steps.py
Unify connection reload accros various feature files into single
step.
> all: use connection reload step

- nmcli/features/connection.feature
> connection: fix connection_user_settings_data test

- nmcli/features/bridge.feature
- nmcli/features/environment.py
- nmcli/features/ipv4.feature
- nmcli/features/team.feature
- nmcli/features/vlan.feature
- prepare/vethsetup.sh
Some failures will occur on 7.5.0
> 7.5.1: enabling tests for z stream

- nmcli/features/environment.py
- prepare/envsetup.sh
It looks like the newest python2 behave has some unicode issues, downgrading a bit
> Downgrade python2 behave and six

- nmcli/features/environment.py
- nmcli/runtest.sh
- nmtui/runtest.sh
> new restraint reporting and SKIP

- nmcli/features/environment.py
this seems to be not working under 7.5
we can revert easily when fixed
https://bugzilla.redhat.com/show_bug.cgi?id=1591188
> ovs: skip on s390x

- nmcli/features/steps/steps.py
- nmtui/features/steps/steps.py
> visible_with_command: run multiple times

- nmcli/features/environment.py
> env: dump status even before restart

- mapper.yaml
test case was not triggered within previous merge
@Build:nm-1-12
> add "ipv4_dhcp-hostname_shared_persists" test to mapper.yaml

- mapper.yaml
- nmcli/features/bond.feature
Add test, that num_grat_arp and num_unsol_na bond options are set properly
https://bugzilla.redhat.com/show_bug.cgi?id=1591734
@Build:nm-1-12
> add 'bond_set_num_grat_arp_unsol_na' test

- mapper.yaml
- nmcli/features/general.feature
- tmp/repro_1555281.py
add 'libnm_async_tasks_cancelable' test
Add test, that libnm async task are cancellable (add_connection_async)
https://bugzilla.redhat.com/show_bug.cgi?id=1555281
@Build:nm-1-12
> add 'libnm_async_tasks_cancelable' test

- nmcli/features/environment.py
Remove skips for tags @simwifi_wpa, @connectivity and @macsec
> Remove skips for RHEL8

- mapper.yaml
- nmcli/features/ethernet.feature
- nmcli/features/general.feature
- nmcli/features/ipv6.feature
- tmp/libnm_snapshot_checkpoint.py
- tmp/nm_agent_prompt_counter.sh
Add tests (to prevent merge conflicts)
* autoconnect_no_secrets_prompt
* libnm_snapshot_rollback...
* ipv6_duid
* ethernet_autoneg_set_speed_duplex
* nmcli_monitor_assertion_con_up_down
fixed:
* CAP_SYS_ADMIN_for_ibft
@Build:nm-1-12
> Add multiple tests 

- nmcli/features/environment.py
This is needed to reset HW address properly.
> env: push mac tag after ethernet

- mapper.yaml
- nmcli/features/gsm.feature
* assisted mode fix
* mtu device check fix
> gsm: fix a bunch of tests for 1.12+ NM

- mapper.yaml
- nmcli/features/ethernet.feature
- nmcli/features/wifi_hwsim.feature
test already exists as 'ethernet_duplex_speed_auto_negotiation'
> remove the test 'ethernet_autoneg_set_speed_duplex'

- nmcli/features/ipv4.feature
- nmcli/features/ipv6.feature
- nmcli/features/steps/steps.py
- nmcli/features/vpn.feature
> steps: fix quoting in "is visible" steps

- nmcli/features/environment.py
Merge all types of service reload to one way.
@Build:nm-1-12
> env: use pkill -HUP NetworkManager to reload

- mapper.yaml
- prepare/envsetup.sh
> envsetup: move some deps to mapper

- mapper.yaml
- nmcli/features/connection.feature
* test that default/single behave the same
* test manualy up connection on multiple devices
* test multiple with autoconnect
* test multiple with reboot
not in TCMS yet, do not know if RHEL 8 will have different plan...
@Build:nm-1-14
> add some test to test connection.multi-connect property

- nmcli/features/ipv4.feature
modify timeouts to be more reliable
> Fix 'ipv4_dhcp_client_id_set' test

- nmcli/features/environment.py
- nmcli/features/ipv4.feature
https://bugzilla.redhat.com/show_bug.cgi?id=1651097
> ensure rp_filters tests behave the same on RHEL8 as on RHEL7

- nmcli/features/environment.py
previously only eth0-10 were unmanaged, not enough for CentOS testing 
setup
> FIX: tag unmanage_eth makes all ethernets unmanaged

- mapper.yaml
- nmcli/features/general.feature
add test, that more than 6 dns-search entries are written to resolv.conf 
file
@Build:nm-1-14
> add 'resolv_conf_search_limit' test

- mapper.yaml
- nmcli/features/dns.feature
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/105
> dns: add tests for restarting dnsmasq when it dies

- mapper.yaml
- nmcli/features/environment.py
- nmcli/features/general.feature
- prepare/captive_portal.sh
Add test, that NM recognizes portal connections.
Test changes DNS to point to localhost and starts local HTTP server, and 
according to response of HTTP server, NM should detect whether 
connection is portal or not.
https://bugzilla.redhat.com/show_bug.cgi?id=1658217
@Build:nm-1-14
> add 'captive_portal_detection' test

- mapper.yaml
- nmcli/features/environment.py
- nmcli/features/vpn.feature
- prepare/iptunnel.sh
> IP tunnel coverage tests

- mapper.yaml
- nmcli/features/steps/steps.py
- nmcli/features/vlan.feature
> add 'vlan_create_macvlan_on_vlan' test

- nmcli/features/general.feature
with less runs prior measuring itself
> make mem consumption test even stricter

- nmcli/features/environment.py
Tag no_config_server is now listing files in rpm and then adding suffix 
'.off' to all files it contains.
This should disable all config files installed by 
NetworkManager-config-server packages, cince NM parses only files with 
'.conf' extension
@Build:nm-1-14
> FIX: 'ipv4_dhcp_client_id_default' failing because no_config_server bug

- mapper.yaml
- nmcli/features/general.feature
Add test checking info messages are printed in editor
https://bugzilla.redhat.com/show_bug.cgi?id=1588995
@Build:nm-1-14
> add 'editor_print_info' test

- mapper.yaml
- nmcli/features/environment.py
- nmcli/features/wifi_hwsim.feature
* wifi_direct: limit to fedora only as 1693684 
* hwsim: p2p disable mac randomization
> hwsim: add wifi_direct test 

- mapper.yaml
- nmcli/features/environment.py
- nmcli/features/general.feature
- nmcli/features/steps/device.py
clean all checkpoints in after_scenario, if tag @checkpoint_remove 
present
Add test, that checkpoint does not keep links to deleted devices
https://bugzilla.redhat.com/show_bug.cgi?id=1578335
@Build:master
> FIX: snapshot cleanups + add "snapshot_deleted_soft_device_dbus_link" test

- nmcli/features/team.feature
https://bugzilla.redhat.com/show_bug.cgi?id=1697844
> adapt 'team_abs_overwrite_watchers' test for nm-1-18
