NetworkManager/NetworkManager-ci

run/centos-ci/nm-centosci.yml
The workspace will always be labeled 'networkmanager' no matter which physical machine it lands on. We should use that for each of the jobs.
=> use the correct node label (networkmanager) so the jobs get run in the correct workspace

nmcli/features/environment.py, nmcli/features/general.feature
This is needed to understand the nature of the rare failures occurring in "profile pickup does not break network service" test: there network service restart fails and we need to have journal logs when this happens (see [rh bz 1455134](https://bugzilla.redhat.com/show_bug.cgi?id=1455134)).
=> Add new "netservice" tag to collect network.service journal logs

nmcli/features/ipv6.feature
Otherwise fd02::2 will be contacted on the wrong interface if there is
an existing default IPv6 route with lower metric.
Fixes: 98fef041b412ee803ecae651b9bc9fb9c0bb25ec
=> ipv6: add explicit route to server in @ipv6_preserve_cached_routes

nmtui/features/ipv4.feature, nmtui/features/ipv6.feature
Since NetworkManager commit 08d7bf5988173f8569b17c646eb1a5c5d9d9340c,
rh#1474295, nmtui guesses the address prefix for RFC1918 private addresses
and uses by default a /64 prefix for IPv6 addresses.
Fix tests `@nmtui_ipv4_addresses_static_no_mask` and `@nmtui_ipv6_addresses_static_no_mask`  for master.
=> tui: adjust tests for guessing address prefix

prepare/racoon.sh
1. Check for number of parameters.
2. Make runnable for users with root priv. Remove "sudo" keywords from the script.
3. Replace all occurrences of /etc/racoon with $RACOON_DIR
=> Make the script more robust

nmcli/features/connection.feature, nmtui/features/ipv4.feature, nmtui/features/ipv6.feature
Previously, NetworkManager would configure default routes via `ip route replace`.
That meant, it needed to take care about not to configure the same dst/plen,metric
route on multiple interfaces, because they would conflict and replace each other.
That was solved by having a NMDefaultRouteManager which corrdinates configuring the
default routes. In face of duplicate routes, it would then bump the metric to avoid
the conflict.
Now, we use instead `ip route append` and each interface can hold conflicting routes
just fine. That makes the bumping of the route no longer necessary. Adjust tests for that.
This adjusts the tests for https://github.com/NetworkManager/NetworkManager/pull/26 . This is already merged on master, so this fixes expected 3 failures there.
=> adjust tests for route metric of default route (th/platform-route-pt4)

nmcli/features/environment.py, prepare/devsetup.sh
We need to avoid installing NM-ppp as it can pull in new NM and that
is not correct in case of older version testing.
=> env: move install of ppp subpackage to env

nmcli/features/ipv6.feature, nmtui/features/ipv6.feature
Since commit 03e1cc96a5dc3d9a9b86f60810a330332c484a94, NetworkManager also
sets the correct route-metric for device-routes for manual IPv6 addresses.
Previously, it would only use the correct metric for IPv4 device-routes
and IPv6 device-routes for IPv6 addresses obtained from SLAAC/autoconf.
Adjust the tests.
__not yet tested__
=> ipv6: adjust tests after setting IPv6 route metric for manual addresses

nmcli/features/bond.feature
It prevents nodes from going down in CICO.
=> bond: switch to ipv4 manual method in arp_all_target

nmcli/features/ipv6.feature
We have few labs but correct prefix is just 2620:52:0 as the rest
may be different from 1086 over 1311 to even different areas.
=> ipv6: make slaac addressing to match different lab too

nmcli/features/general.feature
In 1.9 we changed IPv6 device route metric to the default metric of the device, adapt tests.
=> general: accept new metric for ipv6 device routes

nmcli/features/general.feature
DHCP lease refresh is not predictable in CICO so enabling this needs
veth environment.
=> general: runonce ipv4 rework to use veths

nmcli/features/ipv6.feature
There is no ipv6 default gw in centos CI env so we need to add
one.
=> ipv6: scapy ipv6 packets need default ipv6 gw

nmcli/features/environment.py
this is required to avoid hanging of firewall-cmd: a combination of
start/restart/stop of firewalld service with the "right" timing could
cause the service to hang.
This would cause many test failures due to test timeout:
- no_error_when_firewald_restarted
- show_zones_after_firewalld_install
- connectivity_check
- disable_connectivity_check
- ...
and other failures as NM will try to contact firewalld during connection
activations and will wait 10 seconds for firewalld before giving up and
proceding in the connection activation: in many tests a delay of 10
seconds while connection activation is too much, triggering the test
failure. Some affected tests:
- snapshot_rollback
- snapshot_rollback_all_devices
- snapshot_rollback_all_devices_with_timeout
- snapshot_rollback_soft_device
- …
=> environment: add a sleep after starting firewalld service

nmcli/features/ipv4.feature
IPv6 may be a bit quicker than IPv4 in some cases. In such cases we need to wait for ipv4 too. Especially in IPv4 targeted tests.
=> ipv4: add may fail no to ipv4 tests

nmcli/features/ipv4.feature, nmcli/features/ipv6.feature
There seems to be heavy traffic on eth10 in some environments. Tests are more stable if executed on isolated eth9 instead.
=> move hostname tests to eth9 to avoid heavy traffic on eth10

nmcli/features/bond.feature
It speeds things a bit to have manual ipv4 settings instead of dhcp.
=> bond: use manual ipv4 for bond where dhcp not necessary

nmcli/features/bond.feature
Instead of adding the connection with DHCP and modifying it after it's
already auto-activated with DHCP, create the connection with manual IP
from the beginning.
=> bond: set manual IPv4 when the connection is created

nmcli/features/steps/steps.py
Disable the pager built into readline when testing autocompletion, otherwise pexpect will read only part of the possible completions.
This fixes test 'connection_help'.
Vladimir, please adjust this as you prefer, for example by setting the variable in the global initialization.
=> steps: disable readline pager when testing autocompletion

nmcli/features/bond.feature
Before 1.10.1 the order of bond options was undefined (it was actually
the same in most cases, but it depended on the internal hash function
used by NM). Since 1.10.1 we guarantee that options are returned in
alphabetical order.
=> bond: ensure bond options are in alphabetical order

nmcli/features/wifi.feature
* remove 0 as bogus value as it means no
* set channel to stable wpa1 wifi
* introduce 1.8+ version of novice mode test
=> few 1.10 fixes

nmcli/features/bond.feature
introduce new 1.8.1+ version with removed workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1450219
=> bond device rename

nmcli/features/ipv4.feature
The purpose of the test is to check that NM keeps renewing the lease
for an external DHCP connection. NM used to do that in the past
because it could happen that after a NM restart the connection
matching didn't work and thus the on-disk connection was not
assumed. In such situation, it was considered better to continue doing
DHCP rather than losing connectivity.
Now NM doesn't do connection matching on daemon restart but uses a
state file to know exactly which connection was active. Therefore
there is no risk that a DHCP connection becomes external. If a
connection is external, we should not touch it anymore.
The test should be skipped from NM 1.10.
https://bugzilla.redhat.com/show_bug.cgi?id=1518091
=> ipv4: disable renewal_gw_after_dhcp_outage_for_assumed_var1 on 1.10

nmcli/features/ipv4.feature, nmcli/features/steps/steps.py
We need to check for full 150 seconds that default doesn't reappear
not just that it isn't present once.
=> renewal_gw_after_dhcp_outage_for_assumed_var1 slight modification

nmcli/features/vlan.feature, testmapper.txt
Check that NM correctly recheck parent's MTU when slow DHCP is in
place. Present since 1.10.
https://bugzilla.redhat.com/show_bug.cgi?id=1414901
=> vlan: add 'vlan_mtu_from_parent_with_slow_dhcp' test

nmcli/features/general.feature, testmapper.txt
NM is now able to rollback not only managed state but unmanaged as
well.
https://bugzilla.redhat.com/show_bug.cgi?id=1464904
=> gen: add managed state rollback test

nmcli/features/general.feature, testmapper.txt
Two versions introduced now. Pre 1.8 with ip link up eth0 to up
device slightly earlier to give NM more time and 1.10+ using NM's
new wait-for-carrier=10000 option.
=> runonce: make a test more robust for slow devices

nmcli/features/team.feature
Now the team configuration is checked upon set: in particular, if the
runner selected is unknown, the connection change is dropped.
The config_invalid3 test would fail because the config change with the invalid runner is now early rejected and then the connection can be activated successful . The only invalid team config is the one with an invalid runner.
=> team: config_invalid3: skip test for nm version > nm-1-10-0

nmtui/features/ipv4.feature
This error is unstable in 1.8 branch. We have multiversion test now
=> nmtui: skip error check when invalid route present for 1.8

nmcli/features/team.feature
For various checks there should be nm-team device connected prior
checking anything else especially after reboot.
=> team: wait for nm-team device to be connected

nmcli/features/ipv6.feature, testmapper.txt
Check that ipv4 dad failure doesn't prevent ipv6 addresses and
connection to be upped if failure is not conseder critical.
https://bugzilla.redhat.com/show_bug.cgi?id=1508001
=> ipv6: ipv4 dad fail should not prevent ipv6

nmcli/features/environment.py, nmcli/features/ipv6.feature, nmcli/features/steps/steps.py, testmapper.txt
Check that NM doesn't turn off ipv6 when overtaking renamed device.
https://bugzilla.redhat.com/show_bug.cgi?id=1368018
=> add: persistent_ipv6_after_device_rename

nmcli/features/bridge.feature, testmapper.txt
Check that bridge slave cna be autoconnected when it wasn't explicitely
disconnected before. This allows to restart bridge with new settings via
restarting master only. Slaves will be autoconnected.
https://bugzilla.redhat.com/show_bug.cgi?id=1437598
=> bridge: add bridge_autoconnect_slaves_when_master_reconnected test

nmcli/features/ipv4.feature, testmapper.txt
If onsite is specified there is a device route added which allows
to route to networks that are not directly accessible.
https://bugzilla.redhat.com/show_bug.cgi?id=1428334
=> ipv4: add 'ipv4_route_onsite' test

nmcli/features/ipv6.feature, testmapper.txt
Check that NM doesn't prevent adding ipv6 over manually configured
ipv4 external device.
https://bugzilla.redhat.com/show_bug.cgi?id=1462260
=> ipv6: add 'add_ipv6_over_ipv4_configured_ext_device' test

nmcli/features/team.feature, testmapper.txt
Check that NM reconnects to avilable profile when master team is
gone and slave is disconnected.
https://bugzilla.redhat.com/show_bug.cgi?id=1310676
=> team: add 'reconnect_back_to_ethernet_after_master_delete'

nmcli/features/ethernet.feature, testmapper.txt
Check that reload of leap connection doesn't make it disappear.
https://bugzilla.redhat.com/show_bug.cgi?id=1374660\
@Build:nm-1-10
=> ethernet: add 'preserve_8021x_leap_con' test

nmcli/features/general.feature, testmapper.txt
Make sure that qdisc is removed despite kernel return code. This
blocks re-activation otherwise.
https://bugzilla.redhat.com/show_bug.cgi?id=1527197
@Build:nm-1-10
=> general: reactivate dummy device with qdisc

nmcli/features/general.feature, testmapper.txt, tmp/repro_1512316.sh
Check that NM doesn't touch externally managed dummy device. Script
for adding removing ipv4 and ipv6 addresses is executed few hundred
times.
https://bugzilla.redhat.com/show_bug.cgi?id=1512316
@build:nm-1-10
=> general: add 'do_not_touch_external_dummy' test

nmcli/features/environment.py, nmcli/features/team.feature, testmapper.txt
Sometimes when teamd is slower than usual 100ms wait time in NM is
not enough. This test requies special slowed teamd to properly
show the bug.
https://bugzilla.redhat.com/show_bug.cgi?id=1415641
@Build:nm-1-10
=> team: add 'wait_for_slow_teamd' test

nmcli/features/environment.py, nmcli/features/ipv6.feature, nmcli/features/steps/steps.py, testmapper.txt, tmp/radvd.conf
Check that NM can handle two default routes on the same device for
IPv6 requests coming from multiple radvd servers.
//bugzilla.redhat.com/show_bug.cgi?id=1445417
@Build:nm-1-10
=> ipv6: add 'ipv6_multiple_default_routes' test

nmcli/features/ipv6.feature, testmapper.txt
Check that NM can accept ipv6.routes '1010::1/128 src=2000::2'.
https://bugzilla.redhat.com/show_bug.cgi?id=1452684
@Build:nm-1-10
=> ipv6: add 'ipv6_routes_with_src' test

nmcli/features/bond.feature, nmcli/features/environment.py, nmcli/features/ethernet.feature, testmapper.txt, tmp/nmclient_get_state_flags.py
Check that nmclient correctly shows flags during profile connection
and that it reflects various situations correctly.
https://bugzilla.redhat.com/show_bug.cgi?id=1454883
@Build:nm-1-10
=> bond/ethernet: add 'nmclient_*_get_state_flags' tests

nmcli/features/environment.py, nmcli/features/ipv4.feature, testmapper.txt
Check that NM can handle dhcp-client-id longer than 133 characters
under internal dhcp client.
Test uses 999 chars.
https://bugzilla.redhat.com/show_bug.cgi?id=1531173
@Build:nm-1-10
=> ipv4: add 'ipv4_set_very_long_dhcp_client_id' test

nmcli/features/ipv4.feature, testmapper.txt
Check that NM is OK with externally readded default route as it
always was.
https://bugzilla.redhat.com/show_bug.cgi?id=1503769
@Build:nm-1-10
=> ipv4: add 'ipv4_restore_default_route_externally' test

nmcli/features/wifi_hwsim.feature, testmapper.txt, tmp/nmclient_get_property.py
Check that wireless-hardware-enabled can be properly read from
manager.
https://bugzilla.redhat.com/show_bug.cgi?id=1520398
@Build:nm-1-10
=> nmclient: add 'nmcli_get_wireless_hw_property' test

nmcli/features/bridge.feature, nmcli/features/environment.py, nmcli/features/general.feature, testmapper.txt
* Check that NM can overtake device by changing method to auto.
https://bugzilla.redhat.com/show_bug.cgi?id=1462223
* Add two tests to check whether device is deleted with connection
depending if it existed before NM start or not.
@Build:nm-1-10
=> bridge/general: add device overtaking and bridge deleting tests

run/centos-ci/scripts/build.sh, run/fedora-vagrant/scripts/build.sh
They are needed for sanitizer builds.
=> build.sh: install libasan and libubsan

nmcli/features/team.feature, testmapper.txt
Check that nmcli correctly overwrites link-watchers field.
https://bugzilla.redhat.com/show_bug.cgi?id=1533926
@Build:nm-1-10
=> team: add 'team_abs_overwrite_watchers' test

run/utils/j-dump/j-dump.py
moreover, use the id as the job name (previously was just the last 20
chars of the job url).
=> j-dump: display the date of each job listed

nmcli/features/team.feature
Bugs are fixed so default value can be set via default and sys_prio
should be set to 65535 not 255.
@Build:nm-1-10
=> team: fixes for 1533830 and 1533810

nmcli/features/ipv6.feature
There should be check that NM corrects 1100 mtu to 1280 instead of
setting 1300 directly. This is fixed and 1280 should be set when
1100 was set for IPv6.
@Build:nm-1-6
=> ipv6: correct ipv6_set_ra_announced_mtu test

nmcli/features/general.feature, testmapper.txt
Check that NM start-completed signal (which is consumed by NM-w-o
(wait-online) service can be configured to fit devices whose inits
take longer than default 5s.
https://bugzilla.redhat.com/show_bug.cgi?id=1515027
@Build:nm-1-10
=> general: add 'nm_online_wait_for_delayed_device' test

nmcli/features/general.feature, prepare/devsetup.sh, testmapper.txt
Check that NM waits more than 8 seconds when carrier is flapped
during mtu change for example.
https://bugzilla.redhat.com/show_bug.cgi?id=1487702
@Build:nm-1-10
=> general: add 'wait_10s_for_flappy_carrier' test

nmcli/features/ipv4.feature, testmapper.txt
This checks that when ipv6 is configured but ipv4 loose the lease as DHCP is unreachable, the lease is attempted to be renewed forever (more than the scheduled 3 times, as done when may-fail is no).
Just fixed on master and nm-1-10 (expected to fail in nm-1-8).
@Build:nm-1-10
=> ipv4: add test to check persistent lease renewal

nmcli/features/ipv4.feature
Bringing up tc1 should fail as running dnsmasq prevents shared
connection to start correctly. In older versions connection failed
too, but it took some time. In new version it's immediate.
@Build:nm-1-10
=> ipv4: fix ipv4_method_shared_with_already_running_dnsmasq

nmcli/features/general.feature
Unless https://bugzilla.redhat.com/show_bug.cgi?id=1528071 is resolved
we cannot check metric as it is not updated for dhcp based connections.
@Build:master
=> ipv4: don't check metric in device_reapply_routes in 1.11+

nmcli/features/ipv4.feature, nmcli/features/ipv6.feature, testmapper.txt
This test merges various tests together to save time
* renewal_gw_after_dhcp_outage_for_assumed_var1
* renewal_gw_after_dhcp_outage_for_assumed_var0
* renewal_gw_after_long_dhcp_outage
* renewal_gw_after_dhcp_outage
Those old tests shouldn't be running since 1.11+
@Build:master
=> ipv4: add 'dhcp4_outages_in_various_situation' test

nmcli/features/ipv4.feature, nmcli/features/steps/steps.py, testmapper.txt
Check that we can obtain a new lease immediately after a DHCP NAK.
https://bugzilla.gnome.org/show_bug.cgi?id=783391
=> ipv4: add test for DHCP NAK after expiry

nmcli/features/ipv4.feature
NM changed the way in which lease expirations are handled: before it
stopped the client and respawned it 3 times at fixed intervals (2
minutes), while now it just keep the client running. dhclient tries to
renew the lease immediately and then sleep for a random interval
between 300 and 450 seconds.
Therefore, extend the timeout to be sure the client is able to renew
the lease.
=> ipv4: change timeouts for @dhcp4_outages_in_various_situation

nmcli/features/ipv6.feature
The test is supposed to check that NetworkManager does not add a link
local address. It needs to wait longer to ensure that this doesn't
happen. The previous form did this wrong, which can also be seen because
the test still passes against current master of NetworkManager --
although it would be expected to fail. Fix it.
Fixes: e12de017e6668a48490490abdae0f660024bc51d
---
This is a follow up for #152, which got this wrong.
I tested it, it seems to work. I recommend to merge this patch right away (if you agree), but note that this test is supposed to fail with current master of NetworkManager. It already tests new behavior, that will be merge soon. That is fine.
=> ipv6: fix @ipv6_add_static_address_manually_not_active test to wait

nmcli/features/environment.py, prepare/devsetup.sh, prepare/vethsetup.sh
in some cases this prevents weird slaves after-restart behaviour
@Build:nm-1-8
=> env: disconnect master bond first

mapper.yaml
@RunTests:ethernet_create_with_editor,ethernet_create_default_connection,ethernet_create_ifname_generic_connection,ethernet_connection_up,ethernet_disconnect_device,ethernet_describe_all,ethernet_describe_separately,ethernet_set_matching_mac,no_assumed_connection_for_veth,ethernet_set_invalid_mac,ethernet_set_blacklisted_mac,ethernet_mac_spoofing,ethernet_mac_address_preserve,ethernet_mac_address_permanent,ethernet_mac_address_rhel7_default,ethernet_duplex_speed_auto_negotiation,ethernet_set_mtu,nmcli_set_mtu_lower_limit,ethernet_set_static_configuration,ethernet_set_static_ipv6_configuration,ethernet_set_both_ipv4_6_configuration,nmcli_ethernet_no_ip,nmcli_ethernet_wol_default,nmcli_ethernet_wol_enable_magic,nmcli_ethernet_wol_disable,nmcli_ethernet_wol_from_file,nmcli_ethernet_wol_from_f …
=> Fix kernel-options mapper parameter

mapper.yaml, nmcli/features/bridge.feature, nmcli/features/environment.py, testmapper.txt
autoconnect.slaves should forcefully activate all slaves, even if the
device is currently busy with another profile. That was the case already,
but slightly broken with [1].
This adds two tests, one a general test, and the other where the
profile that should be stolen for activation is the slave profile
itself, but activated previously as a non-slave before being modified.
This is the scenario of bug [2].
[1] https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=0922a177385be188b9c9c8ad39c1068533f5a4b3
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1548265
The second test is not yet expected to pass on master, which is what [2] is all about.
=> bridge: test connection.autoconnect-slaves behavior

nmcli/features/steps/steps.py, nmcli/features/vlan.feature, testmapper.txt
Test that a vlan on a bond parent specified as UUID gets autoconnected at boot.
https://bugzilla.redhat.com/show_bug.cgi?id=1553595
=> vlan: add @vlan_on_bond_autoconnect test

nmcli/features/ipv6.feature
The output on incorrect value changed in 1.11.3
=> ipv6: update ip6-privacy_incorrect_value to new output

nmcli/features/general.feature
Recent failures:
(master, 30.03.2018) [master-upstream-576](https://desktopqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/NetworkManager/job/beaker-NetworkManager-master-upstream/576/)
(pr#103, 24.04.2018) [master-upstream-608](https://desktopqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/beaker-NetworkManager-github-trigger-code-upstream/608/)
=> general: fix race in test setting zone in @show_zones_after_firewalld_install

nmcli/features/ipv4.feature
Tests can run with veth devices instead of ethernet; therefore match
also veth device type in the configuration snippet.
While at it change the connection with autoconnect=no, and manually
activate it. Otherwise, we can't be sure that the test succeeds
because the inifinity timeout was honored; for example, it can happen
that DHCP fails after 45 seconds and autoconnection kicks in.
=> ipv4: fix @dhcp-timeout_default_in_cfg test

nmcli/features/ipv4.feature, nmtui/features/ipv4.feature
Since version 1.11.3 NM automatically adds a device route to the route gateway when it is not directly reachable. See [1]. 
Adjust existing tests.
[1] https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=c9f89cafdf588f443821ccff220283859ab26d1f
=> Adjust unreachable gateway route tests

tmp/repro_1401515.py
For one, iterate the mainloop after making the asynchronous Update2()
request. This way, we don't need to wait unnecessarily long.
And plaster the test script with checks that everything works as
expected. We currently don't have many tests that test libnm via
pygobject. Use the opportunity and make more use of libnm via Python
and see if it all works as epected.
=> connection: add more assertions to tmp/repro_1401515.py

nmcli/features/ipv6.feature
Since the connection gets assumed, NM doesn't delete the original
default route. It seems that sometimes the kernel removes the route,
but the test shouldn't check it.
=> ipv6: don't check for missing original route in persistent_ipv6_routes

nmcli/features/environment.py, nmcli/features/ipv4.feature
and skip rhel7 only tests properly
=> ipv4: make symlink checks better

nmcli/features/steps/steps.py
Often we see that in NATed environment ping is block and thus
few tests are not working as expected (e.g dns-search).
=> steps: change ping to curl for systems wher ping is blocked

nmcli/features/general.feature
=> macsec: we need ping instead of curl so ping multiple times needed

mapper.yaml, nmcli/features/bridge.feature, run/osci/fedora28.tests
It looks we wasn't testing ipv6 on bridge at all. Adding a simple
test to exercise it.
@Build:nm-1-10
=>  bridge: add ipv6 bridge test

nmcli/features/ethernet.feature
Starting from NM versions >= 1.11.4, NM is allowed to set speed
and duplex properties when link auto-negotiation is enabled.
Change the test for link auto-negotiation accordingly.
Note that the NM branch adding the new feature and enabling the test to pass on current NM version (1.11.4) has been merged today.
=> ethernet: update 'ethernet_duplex_speed_auto_negotiation' test

nmcli/features/bond.feature, nmcli/features/environment.py, nmcli/features/general.feature, nmcli/features/ipv4.feature, nmcli/features/ipv6.feature, nmcli/features/steps/steps.py, nmcli/features/team.feature, nmcli/features/vlan.feature
We should stop test if PID was unexpectedly changed after it. This
should show us where crash happened.
@Build:master
=> steps/env: check pid after every step to reveal crash

nmcli/features/ipv6.feature
If the ip6_gre and ip6_tunnel modules were already loaded before the
test, ip6_tunnel removal would fail because ip6_gre depends on it.
=> ipv6: remove ip6_gre module in @ipv6_tunnel_module_removal test

prepare/racoon.sh
This is needed in RHEL 7.6 in order for work correctly.
Extract from the journal where an issue can be seen:
ERROR: /etc/racoon/psk.txt has weak file permission
ERROR: failed to open pre_share_key file /etc/racoon/psk.txt
Context: -rw-r--r-- 1 root root /etc/racoon/psk.txt
FIX:     -rw------- 1 root root /etc/racoon/psk.txt
=> Set correct permissions for preshared keys

mapper.yaml, nmcli/features/ipv4.feature
Add check that setting method shared via nmcli does not remove dhcp-hostname
https://bugzilla.redhat.com/show_bug.cgi?id=1519299
=> ipv4: add "ipv4_dhcp-hostname_shared_persists" test

mapper.yaml, nmcli/features/general.feature
Add check that NM does not overwrite resolv.conf on shutdown
https://bugzilla.redhat.com/show_bug.cgi?id=1541031
@Build:nm-1-12
=> general: add "resolv_conf_overwrite_after_stop" test

mapper.yaml, nmcli/features/general.feature
Add test, that send-sci is configurable on macsec connections and is enabled by default
https://bugzilla.redhat.com/show_bug.cgi?id=1588041
@Build:nm-1-12
=> add "macsec_send-sci_by_default" test

mapper.yaml, nmcli/features/general.feature, nmcli/features/steps/steps.py
Add check, that if resolv.conf is dangling symlink,
it will be followed and new file will be created,
when main.rc-manager=file in config
Add new steps:
"{filename}" is file
"{filename}" is symlink
"{filename}" is symlink with destination "{destination}"
Remove file "{filename}" if exists
Remove symlink "{filename}" if exists
Create symlink {source} with destination {destination}
@Build:nm-1-12
=>  add 'resolv_conf_dangling_symlink' test

mapper.yaml, nmcli/features/general.feature, nmcli/features/ipv4.feature
"ipv4_dhcp-hostname_shared_persists" and "resolv_conf_overwrite_after_stop"
fix versions, add timeouts after NM restarts
@Build:nm-1-12
=> FIX: unstable tests

mapper.yaml
accidentaly removed from mapper in previous merge
@Build:nm-1-12
=> add 'resolv_conf_dangling_symlink' test to mapper.yaml

mapper.yaml, nmcli/features/tuntap.feature, tmp/tuntap_device_kernel_properties.sh
Add test, that kernel, dbus and nmcli returns the same properties of tuntap device
https://bugzilla.redhat.com/show_bug.cgi?id=1547213
@Build:nm-1-12
=> add "tuntap_device_kernel_properties" test

nmcli/features/environment.py, nmcli/features/general.feature, nmcli/features/ipv4.feature, nmcli/features/ovs.feature, nmcli/features/steps/steps.py, nmcli/features/vpn.feature, nmtui/features/environment.py, nmtui/features/ipv4.feature, nmtui/features/steps/steps.py, nmtui/runtest.sh, prepare/envsetup.sh, tmp/dbus-set-gw.py, tmp/network_test.py, version_control.py
we need to make CI both python3 and python2 compatible for newer releases
* encoding fixes in pexpect and check_output 
* install python3 versions of apps
* import strings from futures to be unicode by default
* make exceptions python3 compatible
=> python 2 and 3 compatibility

nmcli/features/environment.py, nmcli/features/ipv4.feature
NM changed behavior upstream with respect to ascii-only
client-ids. Prior to 1.11.2 NM would send the client-id as is; since
1.11.2 the client-id is prefixed with a zero byte.
On RHEL7 (NM 1.12) we reverted the change to maintain the old behavior
and therefore we need to also adjust tests. We have now 3 instances of
the test:
* RHEL7         (old behavior)
* NM <  1.11.2  (old behavior)
* NM >= 1.11.2  (new behavior)
(I have tried only the last two cases, not the first one).
https://bugzilla.redhat.com/show_bug.cgi?id=1613888
=> ipv4: split out client-id test for RHEL7

mapper.yaml, nmcli/features/ipv4.feature
Add test, that if link is down during dhcp lease renewal and then comes back up, address is leased properly
https://bugzilla.redhat.com/show_bug.cgi?id=1573780
@Build:nm-1-12
=> add 'nm_dhcp_lease_renewal_link_down' test

mapper.yaml, nmcli/features/pptp.feature, nmcli/features/steps/steps.py
NM can read passwords for VPNs from file. There was a bug in 1.12
and we were only able to read vpn.secret but vpn.secrets was
supported before. We now support both versions to preserve backward
compatibility.
https://bugzilla.redhat.com/show_bug.cgi?id=1628946
@Build:nm-1-12
=> pptp: add 'pptp_passwd_file' test

mapper.yaml, nmcli/features/dns.feature, nmcli/features/environment.py
Check that NM doesn't crash when veth driver is removed after con
is up with dns=dnsmasq settings enabled.
https://bugzilla.redhat.com/show_bug.cgi?id=1628576
@Build:nm-1-12
=> dns: add 'dns_dnsmasq_driver_removal' test

mapper.yaml, nmcli/features/ethernet.feature
Check that activating a profile wit incorrectly set no password
flag is not stalled but correctly fails after 25s.
https://bugzilla.redhat.com/show_bug.cgi?id=1575501
@Build:nm-1-12
=> ethernet: add '8021x_tls_bad_password_flag' test

mapper.yaml, nmcli/features/steps/steps.py, nmcli/features/vlan.feature
Check that MTU in VLAN->BRIDGE->TEAM->NIC scenario is preserved
after reboot.
https://bugzilla.redhat.com/show_bug.cgi?id=1586191
=> vlan: add 'vlan_over_bridge_over_team_over_nic' test

prepare/envsetup.sh
python3 is default on RHEL8, so python2 libraries ane not needed
installing equivalent libraries for python3 instead
use newer openvswitch, which does not depend on python2
remove instalation of wireshark, wireshark-cli is enough
=> RHEL8 - fix installed packages in envsetup

nmtui/features/general.feature
NM since 1.14 creates "<con-name>.nmconnection" file instead of "<con-name>" file in "/etc/NetworkManager/system-connections/"
@Buid:nm-1-14
=> Fix 'nmtui_dsl_create_default_connection' test

nmcli/features/environment.py
* skipping gsm_sim on not intel
* skipping pppoe on aarch64 due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1643954
=> Architecture dependent skippers

nmcli/features/general.feature, nmcli/features/steps/steps.py
FIX '* Force renew IPv6 for "testG"' step:
* captured ipv6 included newline causing problems
* use "ip flush" to remove old address (no need to check that address is deleted afterwards)
=> FIX: run_once_ip6_renewal

nmcli/features/environment.py, nmcli/features/general.feature
Add "ifup_ifdown_scripts" test
test the behaviour of ifup/ifdown script
since nm-1-14 these scripts are using nmcli
+ create rhel8_only tag - may be useful in some tests
+ fix 'autoconnect_no_secrets_promt' test - using wrong connection name
=> Add 'ifup_ifdown_script' test

mapper.yaml, nmcli/features/environment.py, nmcli/features/libreswan.feature, prepare/libreswan.sh
test that reimporting exported connection does not drop options
test is using IKEv2 - modified prepare script to accept IKE version as argument
FIX: retab prepare/libreswan.sh file
ADD: dummy test 'libreswan_onfigurable_options'
https://bugzilla.redhat.com/show_bug.cgi?id=1633174
@Build:nm-1-14
=> Add 'libreswan_reimport' test using IKEv2

nmcli/features/ipv4.feature
Fix failing test, compare to default value in 
/proc/sys/net/ipv4/conf/default/rp_filter, not to fixed value.
=> FIX: 'ipv4_rp_filter_reset' not in RHEL package

mapper.yaml, nmcli/features/ipv4.feature
Add test, that NM has right settings regarding DHCP client-id in RHEL8
https://bugzilla.redhat.com/show_bug.cgi?id=1640494
=> add 'nm_dhcp_client_id_default_settings' test

mapper.yaml, nmcli/features/ipv4.feature
Add test, that client-id is not read from lease file after NM restart
https://bugzilla.redhat.com/show_bug.cgi?id=1642023
@Build:nm-1-14
=> add 'ipv4_dhcp_client_id_change_lease_restart' test

nmcli/features/libreswan.feature
rhel8_only tag caused skipping, replaced by not_in_rhel7
the purpose of this is that RHEL7 have old version of libreswan plugin, 
so the test would fail
=> FIX: 'libreswan_configurable_options_reimport' test tag

mapper.yaml, nmcli/features/ipv4.feature
add test, that prefix route is preserved after setting link down and up 
manualy
https://bugzilla.redhat.com/show_bug.cgi?id=1636715
@Build:nm-1-14
=> add 'ipv4_prefix_route_missing_after_ip_link_down_up' test

mapper.yaml, nmcli/features/general.feature, tmp/repro_1643085.py
use reproducer from Gris Ge 
https://bugzilla.redhat.com/show_bug.cgi?id=1642625#c11 
https://bugzilla.redhat.com/show_bug.cgi?id=1643085
FIX: nmcli_monitor_assertion_con_up_down uses eth2 instead of eth8
@Build:nm-1-14
=> add "libnm_async_activation_cancellable_no_crash" test

nmcli/features/libreswan.feature
NetworkManager now adds '.nmconnection' suffix to the keyfiles.
Let the test use the expected file suffix.
See https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=4ca7fa7f4
(This should fix failures on github gating for custom branches)
=> libreswan: adapt vpn_keep_username_from_data to nm ver 1.4

mapper.yaml, nmcli/features/vlan.feature
Add test, that NM does not delete static route when changing MAC address 
of the device.
Thanks @thaller for reproducer:
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/merge_requests/54#note_82187
https://bugzilla.redhat.com/show_bug.cgi?id=1659063
@Build:nm-1-14
=> add "static_route_persists_mac_change" test

mapper.yaml, nmcli/features/bridge.feature
Add test, that devices created by initrd are mapped to existing 
connections, NM should not create temporary connection, even if device
parameters slightly differ.
https://bugzilla.redhat.com/show_bug.cgi?id=1593939
@Build:nm-1-14
=> add 'bridge_detect_initrd_device' test

mapper.yaml, nmcli/features/ipv4.feature, nmcli/features/steps/steps.py
add 'ipv4_dhcp_client_id_default' tests
Add tests, that with internal plugin, client ID is:
* duid is used with NM 1.12-1.14
* duid is used on RHEL7 
* mac is used with NM 1.16+
* mac is used on RHEL8
https://bugzilla.redhat.com/show_bug.cgi?id=1661165
@Build:nm-1-14
=> add 'ipv4_dhcp_client_id_mac_default' test

nmcli/features/environment.py
Not bundling a logs will shorten time of execution. For 1 hour in case of 1.12. from 5:45 to 4:45. 
* TCPdump is removed and will be available just via tcpdump tag
* Journal is not attached by default as quite large
* dump will not be done after passed test before and after clean up , just before test
=> env: append logs for failed tests only

mapper.yaml, nmcli/features/ethernet.feature
Add test, that NM is able to change not fixed ethtool feature
Add test, that connection activates even if ethtool feature is fixed and 
does not match actual state
https://bugzilla.redhat.com/show_bug.cgi?id=1335409
@Build:nm-1-14
=> add ethtool features tests

mapper.yaml, nmcli/features/connection.feature, nmcli/features/steps/steps.py
test basic functionality of `nmcli -o con show $PROFILE`
FIX: reindent end of file
FIX: harmless typo in steps.py
https://bugzilla.redhat.com/show_bug.cgi?id=1434527
@Build:nm-1-14
=> add 'connection_short_info' test

nmcli/features/environment.py, nmcli/features/general.feature, nmcli/features/steps/steps.py
Append/remove 1.2.3.4 static.redhat.com to /etc/hosts to make
checker unreachable instead of doing firewalld --panic-on/off.
=> gen: fix connectivity checks tests

mapper.yaml, nmcli/features/general.feature, nmcli/features/steps/steps.py
Add check, that connection assistant prints connection type 
possibilities after double tab
https://bugzilla.redhat.com/show_bug.cgi?id=1588952
@Build:nm-1-14
=> add 'nmcli_novice_print_types' test

mapper.yaml, nmcli/features/general.feature
nmcli sometimes crash with SIGSEGV when modifying 
'802-1x.altsubject-matches' property of a connection
The test changes this property 8 times, to increase probability of 
SIGSEGV
https://bugzilla.redhat.com/show_bug.cgi?id=1576490
@Build:nm-1-14
=> add 'nmcli_modify_altsubject-matches' test

nmcli/features/bond.feature, nmcli/features/steps/steps.py
Modify test to use kill signal 9 if NM version is at least 1.14
https://bugzilla.redhat.com/show_bug.cgi?id=1593282
@Build:nm-1-14
=> hard kill (kill -9) in the test 'bond_leave_L2_only_up_when_going_down'

mapper.yaml, nmcli/features/general.feature, tmp/libnm_snapshot_checkpoint.py
Add test, that deystroing checkpoint object before rollback succeds, and 
that after rollback it fails.
It is important to exit with error, when destroying checkpoint object 
which is alredy rollbacked or destroyed.
https://bugzilla.redhat.com/show_bug.cgi?id=1574565
=> add 'libnm_snapshot_destroy_after_rollback' test

mapper.yaml, nmcli/features/environment.py, nmcli/features/vpn.feature, prepare/wireguard.sh
Wireguard is so far working only on RHEL 8. On RHEL 7 wireguard module 
is unable to compile, due to older kernel.
Also, at least NM 1.16 required, to be able to add wireguard connection.
@Build:nm-1-16
=> Add simple wireguard test

nmcli/features/general.feature
the bug was fixed also in older versions of NM, runngin since version 1.10 instead of 1.14
already tested, should not fail
=> FIX: version in 'libnm_async_activation_cancelable_no_crash' test

mapper.yaml, nmcli/features/team.feature
add test, that it is possible to set vlanid property of link-watchers in 
team connection
https://bugzilla.redhat.com/show_bug.cgi?id=1652931
@Build:nm-1-16
=> add 'team_abs_set_link_watchers_arp_ping_vlanid' test
